import { Container, SimpleGrid, useMantineTheme } from "@mantine/core";
import Head from "next/head";
import { useMemo } from "react";

import { PostCard } from "@/components/PostCard";
import { useGetCategories } from "@/queries";
import { CustomNextPage } from "@/types/dts";

const mockdata = [
  {
    category: "decorations",
    footer: "733 people liked this",
    author: {
      name: "Elsa Gardenowl",
      image:
        "https://images.unsplash.com/photo-1628890923662-2cb23c2e0cfe?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=200&q=80",
    },
    title: "Top 10 places to visit in Norway this summer",
    image:
      "https://images.unsplash.com/photo-1527004013197-933c4bb611b3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80",
    date: "August 18, 2022",
  },
  {
    category: "decorations",
    footer: "733 people liked this",
    author: {
      name: "Elsa Gardenowl",
      image:
        "https://images.unsplash.com/photo-1628890923662-2cb23c2e0cfe?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=200&q=80",
    },
    title: "Best forests to visit in North America",
    image:
      "https://images.unsplash.com/photo-1448375240586-882707db888b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80",
    date: "August 27, 2022",
  },
  {
    category: "decorations",
    footer: "733 people liked this",
    author: {
      name: "Elsa Gardenowl",
      image:
        "https://images.unsplash.com/photo-1628890923662-2cb23c2e0cfe?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=200&q=80",
    },
    title: "Hawaii beaches review: better than you think",
    image:
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80",
    date: "September 9, 2022",
  },
  {
    category: "decorations",
    footer: "733 people liked this",
    author: {
      name: "Elsa Gardenowl",
      image:
        "https://images.unsplash.com/photo-1628890923662-2cb23c2e0cfe?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=200&q=80",
    },
    title: "Mountains at night: 12 best locations to enjoy the view",
    image:
      "https://images.unsplash.com/photo-1519681393784-d120267933ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80",
    date: "September 12, 2022",
  },
];

const Home: CustomNextPage = () => {
  const theme = useMantineTheme();
  const { data: posts, isLoading: postsLoading } = useGetCategories();
  const cards = useMemo(
    () =>
      posts?.map((article) => (
        <PostCard theme={theme} post={article} key={article.title} />
      )),
    [posts, theme]
  );
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container
        py="xl"
        sx={{
          width: "100%",
          maxWidth: "100%",
          marginLeft: 0,
          marginRight: 0,
        }}
      >
        <SimpleGrid
          sx={{
            width: "100%",
          }}
          cols={3}
          spacing="md"
          breakpoints={[
            { maxWidth: "md", cols: 1 },
            {
              maxWidth: "lg",
              cols: 2,
            },
          ]}
        >
          {cards}
        </SimpleGrid>
      </Container>
    </>
  );
};
export default Home;
