import { Container, SimpleGrid, useMantineTheme } from "@mantine/core";
import moment from "moment";
import Head from "next/head";
import { useMemo } from "react";

import { PostCard } from "@/components/PostCard";
import { useGetPosts } from "@/queries";
import { CustomNextPage } from "@/types/dts";

const Home: CustomNextPage = () => {
  const theme = useMantineTheme();
  const { data: posts, isLoading: postsLoading } = useGetPosts();
  const cards = useMemo(
    () =>
      posts
        ?.sort(
          (a, b) => moment(b.updatedAt).unix() - moment(a.updatedAt).unix()
        )
        ?.map((article) => (
          <PostCard theme={theme} post={article} key={article.title} />
        )),
    [posts, theme]
  );
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container
        py="xl"
        sx={{
          width: "100%",
          maxWidth: "100%",
          marginLeft: 0,
          marginRight: 0,
        }}
      >
        <SimpleGrid
          sx={{
            width: "100%",
          }}
          cols={3}
          spacing="md"
          breakpoints={[
            { maxWidth: "md", cols: 1 },
            {
              maxWidth: "lg",
              cols: 2,
            },
          ]}
        >
          {cards}
        </SimpleGrid>
      </Container>
    </>
  );
};
export default Home;
