import { Button } from "@mantine/core";
import Head from "next/head";
import { useRouter } from "next/router";
import { signOut, useSession } from "next-auth/react";

import { CustomNextPage } from "@/types/dts";

const Home: CustomNextPage = () => {
  const { data, status } = useSession();
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {data?.user ? (
          <p>Hello, {data?.user?.name}!</p>
        ) : (
          <Button onClick={async () => await router.push("/auth/signin")}>
            Sign In
          </Button>
        )}
        {status === "authenticated" && (
          <Button onClick={() => signOut()}>Sign Out</Button>
        )}
      </main>
    </>
  );
};
export default Home;
